name: redbull_code_bech_v1
description: Game tournaments app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.7.33
  flutter_hooks: ^0.18.0
  introduction_screen: ^2.1.0
  lottie: ^1.2.1
  font_awesome_flutter: ^9.2.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  provider: ^6.0.1
  flutter_login: ^3.0.0
  google_nav_bar: ^5.0.5
  firebase_auth: ^3.2.0
  horizontal_card_pager: ^1.1.1
  vertical_card_pager: ^1.5.0
  cloud_firestore: ^3.1.0
  google_sign_in: ^5.2.1
  draggable_home: ^1.0.2
  convex_bottom_bar: ^3.0.0
  firebase_messaging: ^11.1.0
  permission_handler: ^8.3.0
  babstrap_settings_screen: ^0.1.1
  direct_select: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/red-bull-code-app-icon.png"

flutter_native_splash:
  color: "#313131"
  image: assets/red-bull-code-app-icon-large.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/trophy.jpg
    - assets/red-bull-code-app-icon.png
    - assets/red-bull-code-app-icon-large.png
    - assets/rives/loader.riv

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Black.ttf
        - asset: fonts/Lato/Lato-BlackItalic.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-BoldItalic.ttf
        - asset: fonts/Lato/Lato-Italic.ttf
        - asset: fonts/Lato/Lato-Light.ttf
        - asset: fonts/Lato/Lato-LightItalic.ttf
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Thin.ttf
        - asset: fonts/Lato/Lato-ThinItalic.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
