name: redbull_code_bech_v1
description: Game tournaments app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.7.33
  flutter_hooks: ^0.18.0
  introduction_screen: ^2.1.0
  lottie: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/red-bull-code-app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/trophy.jpg
    - assets/red-bull-code-app-icon.png
    - assets/rives/loader.riv

